services:
  - type: web
    name: qr-attendance
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
